general:
  task: 'cv'
  subtask: 'imclf'
  project_name: 'project_1'
  exp_name: 'experiment_1'

model:
  architecture: 'mobilenet_v2'
  freeze_backbone: true
  pretrained: true

data:
  dataset_folder: 'projects/datasets/dogscats/'
  width: 224
  height: 224
  labels:
    - 'cat'
    - 'dog'
  train_len: -1
  val_len: -1
  transforms_train: 'default'
  transforms_val: 'default'

trainer:
  gpus: '3'
  max_epochs: 10

training:
  seed: 42
  batch_size_train: 8
  shuffle_train: True
  batch_size_val: 8
  shuffle_val: False
  workers: 0
  optimizer:
    name: 'Adam'
    params:
      lr: 0.00005
  criterion: 'CrossEntropyLoss'

checkpoint_callback:
  mode: max
  monitor: val_acc
  save_top_k: 1
  verbose: True
  filename: '{epoch}_{val_acc:.2f}'
