general:
  task: 'cv'
  subtask: 'imclf'
  project_name: 'project_test'
  exp_name: 'experiment_1'

model:
  architecture: 'mobilenet_v2'
  freeze_backbone: true
  pretrained: true

data:
  dataset_folder: 'projects/datasets/dogscats/'
  width: 224
  height: 224
  labels:
    - 'cat'
    - 'dog'
  train_len: 500
  val_len: 150
  shuffle_train: True
  shuffle_val: False
  transforms_train: 'default'
  transforms_val: 'default'

trainer:
  gpus: null
  max_epochs: 5

training:
  seed: 42
  batch_size_train: 8
  batch_size_val: 8
  workers: 0
  criterion: 'CrossEntropyLoss'

optimizer:
  name: 'Adam'
  params:
    lr: 0.00005

scheduler:
  name: ReduceLROnPlateau
  params:
    factor: 0.6
    patience: 25
    min_lr: 1.0e-5
    verbose: true

checkpoint_callback:
  mode: max
  monitor: val_acc
  save_top_k: 1
  verbose: True
  filename: '{epoch}_{val_acc:.3f}'
