general:
  task: 'cv'
  subtask: 'imsgm'
  project_name: 'project_2'

data:
  dataset_folder: 'projects/datasets/shapes/'
  width: 256
  height: 256
  num_classes: 1
  transforms_train: 'default'
  transforms_val: 'default'
  in_channels: 3

model:
  architecture: 'FPN'
  backbone: 'mobilenet_v2'
  criterion: 'JaccardLoss'
  optimizer: 'Adam'
  pretrained: true
  batch_size: 8
  lr: 0.001
  max_epochs: 5
