general:
  task: 'cv'
  subtask: 'imsgm'
  project_name: 'project_2'
  exp_name: 'experiment_2'

model:
  architecture: 'FPN'
  backbone: 'mobilenet_v2'
  pretrained: true

data:
  dataset_folder: 'projects/datasets/shapes_2ch/'
  use_rle: true
  width: 256
  height: 256
  num_classes: 2
  transforms_train: 'default'
  transforms_val: 'default'
  in_channels: 3
  train_len: -1
  val_len: -1
  shuffle_train: True
  shuffle_val: False

trainer:
  gpus: '3'
  max_epochs: 5

training:
  seed: 42
  batch_size_train: 32
  batch_size_val: 8
  workers: 0
  criterion: 'JaccardLoss'

optimizer:
  name: 'Adam'
  params:
    lr: 0.0002

scheduler:
  name: ReduceLROnPlateau
  params:
    factor: 0.6
    patience: 25
    min_lr: 1.0e-5
    verbose: true

checkpoint_callback:
  mode: max
  monitor: val_iou
  save_top_k: 1
  verbose: True
  filename: '{epoch}_{val_iou:.3f}'
