general:
  task: 'cv'
  subtask: 'imsgm'
  project_name: 'project_2'
  exp_name: 'experiment_1'

model:
  architecture: 'FPN'
  backbone: 'mobilenet_v2'
  pretrained: true

data:
  dataset_folder: 'projects/datasets/shapes/'
  width: 256
  height: 256
  num_classes: 1
  transforms_train: 'default'
  transforms_val: 'default'
  in_channels: 3
  train_len: -1
  val_len: -1

trainer:
  gpus: '3'
  max_epochs: 20

training:
  seed: 42
  batch_size_train: 8
  shuffle_train: True
  batch_size_val: 8
  shuffle_val: False
  workers: 0
  criterion: 'JaccardLoss'

optimizer:
  name: 'Adam'
  params:
    lr: 0.0002

scheduler:
  name: ReduceLROnPlateau
  params:
    factor: 0.6
    patience: 25
    min_lr: 1.0e-5
    verbose: true

checkpoint_callback:
  mode: max
  monitor: val_iou
  save_top_k: 1
  verbose: True
  filename: '{epoch}_{val_iou:.2f}'
