dataset_folder: 'projects/datasets/shapes/test/'
data_len: -1
shuffle: false
num_workers_test: 0
batch_size: 64
gpus: '0'
ckpt_path: 'projects/project_2/experiment_1_20210417T140139/weights/epoch=4_val_iou=0.969_20210417T140139.ckpt'